### ISSUE TITLE
Check command?

### ISSUE THREAD

**Issue by Korijn** [Madoshakalaka/pipenv-setup#1]
Is it a lot of trouble to add a `pipenv-setup check` command that merely validates if the Pipfile and setup.py file are synchronized, with corresponding exit codes?

**Comment by Madoshakalaka** [comment]
shouldn't be hard. I'll add it👍

**Comment by Madoshakalaka** [comment]
I'm wrapping up check functionality. In the 2.0.0 version I'm going to introduce.
'$ pipenv-setup' is going to be a pipenv-styled help output. The original functionality is going to be 
 moved to `sync` subcommand:
![Capture](https://user-images.githubusercontent.com/44753941/63634754-05c7b680-c618-11e9-9ca5-92ddb6c8dfda.PNG)

**Comment by Korijn** [comment]
Great! That allows to use check in CI and use the sync command manually.

**Comment by Madoshakalaka** [comment]
@Korijn just release 2.0.3 that features these functionality
