### ISSUE TITLE
Update colorama to >= 0.4.3

### ISSUE THREAD

**Issue by NaffanDroo** [Madoshakalaka/pipenv-setup#19]
This utility is extremely useful, however most other packages that this might need to coexist with seem to require at least 0.4.3 of colorama.

The error I seem to receive (strangely when running only in a container (Python 3.7.6) is a `ModuleNotFoundError: No module named 'colorama'` from `main.py` line 18.

I'd have thought pipenv itself on my project would have complained about the missmatch, I am making an assumption that it's not finding colorama because a later version is installed?

I'm using `v2.2.5` of pipenv-setup.

**Comment by Madoshakalaka** [comment]
Hi Python 3.3 3.4 has reached end of life and many packages stopped supporting them. colorama is one of them.

pipenv-setup used to have `colorama ~=0.4.1`, and then colorama releases 0.4.3 which dropped support for python 3.4. Limiting colorama to <=0.4.1 is a measure to continue support for our claimed 3.4 compatibility.

I'm dropping official 3.4 support and add colorama~=0.4.3 again in Pipfile. Thanks for your issue!

**Comment by Madoshakalaka** [comment]
Just released 3.0.0 in which colorama is up to date!

**Comment by bryant-finney** [comment]
Adding this requirement to colorama introduced an incompatibility with [aws-cli](https://pypi.org/project/awscli/), which requires `colorama < 0.4.2`. I would suggest specifying a broader requirement for the `colorama` version in this project to avoid this. 

Would you like me to open a new issue for this?

**Comment by Madoshakalaka** [comment]
@bryant-finney actually I did a oopsies. I meant ~=0.4 all the time (updates without breaking backwards compatibility). Thanks for correcting me

**Comment by bryant-finney** [comment]
Happy to help out!

**Comment by NaffanDroo** [comment]
Wow I really need to sort out my email notifications on this one - thanks for the hard work and so quickly! 🎉
