### ISSUE TITLE
install from GitHub feature branches do not transfer to setup.py correctly

### ISSUE THREAD

**Issue by coltonbh** [Madoshakalaka/pipenv-setup#24]
The install in my Pipfile is as follows:

`ids = {editable = true,git = "ssh://git@github.com/qbio/immutable-data-store.git",ref = "feature/s3-key-manipulation"}`

The transferred package to setup.py is:

`"git+ssh://git@github.com/qbio/immutable-data-store.git@3636a992596cb555d08e8d31c4854a15e9d006a7#egg=ids"`

It appears `pipenv-setup` transfers the commit hash instead of the branch name. Which then causes future invocations of `pipenv-setup check` to fail.

**Comment by NPann** [comment]
Seems to be addressed in #21

**Comment by coltonbh** [comment]
Correct! Thank you.
