### ISSUE TITLE
Setup.py template missing from distribution

### ISSUE THREAD

**Issue by curiousstranger** [Madoshakalaka/pipenv-setup#3]
I have a private project I've been managing with pipenv.  Installed pipenv-setup to make it easier to distribute internally, but am running into a 'Can not find setup.py template file' error when trying to generate the initial setup.py

$ pipenv install --dev pipenv-setup 
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing pipenv-setup…
Adding pipenv-setup to Pipfile's [dev-packages]…
✔ Installation Succeeded
Pipfile.lock (b9df1f) out of date, updating to (5cc7a7)…
Locking [dev-packages] dependencies…
✔ Success!
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (b9df1f)!
Installing dependencies from Pipfile.lock (b9df1f)…
$ grep -A 6 pipenv-setup Pipfile.lock
        "pipenv-setup": {
            "hashes": [
                "sha256:9c8bb190960150dc437bcb815bfa0b916ea6b76897488694e479efe79864ee6d"
            ],
            "index": "pypi",
            "version": "==2.1.6"
        },
$ pipenv-setup sync
setup.py not found under current directory
Creating boilerplate setup.py...
[Errno 2] No such file or directory: '[virtualenv-path-elided]/lib/python3.7/site-packages/pipenv_setup/res/setup_template.py'
pipenv-setup failed to create setup.py
Can not find setup.py template file

$ ls -lR [virtualenv-path-elided]/lib/python3.7/site-packages/pipenv_setup
total 128
-rw-r--r--   1 mcable  staff      0 Oct 17 13:10 __init__.py
-rw-r--r--   1 mcable  staff    292 Oct 17 13:10 __main__.py
drwxr-xr-x  13 mcable  staff    416 Oct 17 13:10 __pycache__
-rw-r--r--   1 mcable  staff    379 Oct 17 13:10 constants.py
-rw-r--r--   1 mcable  staff  19718 Oct 17 13:10 inconsistency_checker.py
-rw-r--r--   1 mcable  staff   2315 Oct 17 13:10 lock_file_parser.py
-rw-r--r--   1 mcable  staff   7557 Oct 17 13:10 main.py
-rw-r--r--   1 mcable  staff    608 Oct 17 13:10 msg_formatter.py
-rw-r--r--   1 mcable  staff   1727 Oct 17 13:10 pipfile_parser.py
-rw-r--r--   1 mcable  staff   1182 Oct 17 13:10 setup_filler.py
-rw-r--r--   1 mcable  staff   2965 Oct 17 13:10 setup_parser.py
-rw-r--r--   1 mcable  staff   5391 Oct 17 13:10 setup_updater.py

**Comment by Madoshakalaka** [comment]
this is a packaging problem I've noticed earlier. I'll fix it soon!

**Comment by Madoshakalaka** [comment]
just published 2.1.7 with this fixed!
