### ISSUE TITLE
Security Patches

### ISSUE THREAD

**Issue by bryant-finney** [Madoshakalaka/pipenv-setup#5]
A I noticed a handful of the dependencies in test data packages are flagged with security vulnerabilities. 

Do you think it's worth running through the github auto-generated PRs to update these test data packages? Or is it unsafe to assume that vulnerable test packages are not intended in these test cases?

**Comment by Madoshakalaka** [comment]
those security alerts are not at all relevant, as the packages listed in the test data are never used. I manually disabled the alerts in this repo. I think a bot is very welcome. Yet I've never set up one before

**Comment by Madoshakalaka** [comment]
you look enthusiastic about pipenv-setup. Do you mind me adding you as a maintainer :D

**Comment by bryant-finney** [comment]
Sure! Happy to contribute what I can (though my availability is limited atm). I've started using `pipenv-setup` on a couple of new projects, and the package seems like another step in the right direction towards dependency management through an appliation's lifecycle.

**Comment by Madoshakalaka** [comment]
I'm very glad to hear that!
