### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by jshwi** [Madoshakalaka/pipenv-setup#74]
Would the author have any plans for this project moving forward?

**Comment by Madoshakalaka** [comment]
@jshwi @bryant-finney I feel deeply sorry for ignoring people's pull requests and not keeping the project up to date. I have sent Bryant a package owner invite and a maintainer invite. I sincerely wish this project can fall into good hands and get revitalized.

**Comment by bryant-finney** [comment]
> @jshwi @bryant-finney I feel deeply sorry for ignoring people's pull requests and not keeping the project up to date. I have sent Bryant a package owner invite and a maintainer invite. I sincerely wish this project can fall into good hands and get revitalized.

Okay much appreciated!

I'm closing this issue 🙂
