### ISSUE TITLE
error: Library stubs not installed for "six" (or incompatible with Python 3.7)

### ISSUE THREAD

**Issue by jshwi** [Madoshakalaka/pipenv-setup#77]
In relation to: https://github.com/Madoshakalaka/pipenv-setup/pull/76#pullrequestreview-799484573

**Comment by jshwi** [comment]
@bryant-finney https://github.com/Madoshakalaka/pipenv-setup/pull/75#issuecomment-962797440
I don't have experience with Gitlab's CI, but while we're at it I could attempt to put together a GH action workflow for the points listed on the Gitlab fork.

**Comment by bryant-finney** [comment]
@jshwi 
Sounds solid! I got the GitLab pipeline to run the test suite for Python 3.6, 3.7, and 3.8 (using the base Python Docker images for each). It'll be easy to extend for 3.9/3.10 whenever we get there.

I'm sure you noticed, but [all three `tox` jobs failed](https://gitlab.com/bryant.finney/pipenv-setup/-/pipelines/40386411) haha.

I was able to get it to run locally with the following (IIRC; I had to hop off before I could commit and push):
- add `mypy = "*"` to `dev-paclages`
  - I think you can alternatively resolve the errors by upgrading `pytest-mypy`
- add `types-six = "*"` to `dev-paclages`
- add `pyparsing = ”~=2”` to ` packages`
  - this one was sneaky and took a wrong to complete
Hope that helps!

Also, I still need to update the issue, but I'd like to separate `pytest` and `mypy` into separate jobs.

**Comment by jshwi** [comment]
@bryant-finney
Can be a bit hit and miss when running local/remote with the CI! 
I need to look into how Gitlab does things.

If you're ever interested in checking out GH actions, and don't want to have to run remote to test, I've been using https://github.com/nektos/act with Docker.

I'll keep an eye on Gitlab so I'm no trying to re-invent the wheel :D

**Comment by bryant-finney** [comment]
@jshwi 

I just found pyparsing/pyparsing#329 ; that bug is actually what is responsible for the `pyparsing` issue [I mentioned earlier](https://github.com/Madoshakalaka/pipenv-setup/issues/77#issuecomment-962829823) haha

Setting `pyparsing!=3.0.5` seems to be a better solution for this problem. After doing so, adding `types-six`, and updating `pytest-mypy` in [87300b](https://gitlab.com/bryant.finney/pipenv-setup/-/commit/87300b5cb80644189cf579f823429a7dfe589ffd), the `tox` jobs are passing :)

**Comment by jshwi** [comment]
@bryant-finney https://github.com/Madoshakalaka/pipenv-setup/issues/77#issuecomment-963172437
I'll check that out, Gitlab seems to have a lot of good stuff out of the box

@bryant-finney That's a really good find, I tried adding  the types as is, and it didn't work for me haha

**Comment by bryant-finney** [comment]
@jshwi yeah that's been my experience with GitLab: as an all-in-one solution for DevOps, it's pretty tightly integrated across the average project's SDLC. 

On which note: I added jobs for executing the test suite using Windows-based runners [in MR !78](https://gitlab.com/bryant.finney/pipenv-setup/-/merge_requests/78) 😃 also, when making changes to `Pipfile`, I went ahead and ran [prettier](https://github.com/prettier/prettier) on the JSON/YAML/TOML files for consistency (ultimately I hope to configure [pre-commit](https://github.com/pre-commit/pre-commit) to handle these trivialities automatically).

**Comment by jshwi** [comment]
@bryant-finney  I made a gitlab account a few days ago, and I've added that fork as a remote :) I'm gonna playaround with gitlab for a bit.

I've tried your latest commit on the GH actions runner and it's looking good. I'm having a look at the travis config, and it looks like there's some complexity in running the osx builds per python version, but it should be pretty doable once I get into it.

Looks like this is coming back to life :smiley:

**Comment by bryant-finney** [comment]
@jshwi excellent! I haven't tried osx runners in GL yet; just windows runners. I know osx runners are supported, but it looks like the project needs to request them specifically. I'll have better info when I dig in again. 🙂

On which note, it might be a couple of days before I can get back to finishing that GL MR; but definitely don't hesitate to reach out if you need any permissions or anything!

**Comment by jshwi** [comment]
@bryant-finney awesome! no sweat, I'll keep plodding along. if I need to I'll drop you a ping, but get back whenever you can, shouldn't be a problem. cheers :smile:

**Comment by jshwi** [comment]
@bryant-finney https://github.com/Madoshakalaka/pipenv-setup/pull/79 preview, if you would like to review the progress

**Comment by jshwi** [comment]
Would I be OK to close this one off? :smile:

**Comment by bryant-finney** [comment]
@jshwi absolutely!
